/**
 * Models mapping exactly to the responses generated by StationlyBE (Java)
 * This ensures strict contract adherence so UI integrations do not break.
 */

export interface TransportMode {
    modeName: string;
    displayName: string;
    /** Epoch millis (integer) — replication watermark. */
    lastUpdatedTime?: number;
}

export interface LineInfo {
    id: string;
    name: string;
    modeName: string;
    /**
     * Short display form ("Picc.", "H&C") — see `TFL_LINE_SHORT_NAMES`.
     *
     * Optional, and absent rather than null when there is none (bus routes,
     * whose id is already the shortest true label). Clients treat absence as
     * "fall back to your own rule", so it must not be echoed as the full name.
     */
    shortName?: string;
}

export interface Destination {
    id: string;
    name: string;
    label?: string;
}

export interface DirectionInfo {
    direction: string; // e.g., inbound, outbound
    destinations: Destination[];
}

export interface LineRouteResponse {
    id: string;
    name: string;
    modeName: string;
    directions: DirectionInfo[];
}

export interface PredictionItem {
    destId: string;
    platform: string;
    eta: string; // ISO-8601
    displayName: string;
    /**
     * Which branch this service takes, when TfL labels one ("Morden via Bank"
     * → `bank`). See utils/viaKey.ts.
     *
     * ## ABSENT means "no branch", and absent is the normal case
     * The field is omitted entirely rather than sent as null. Only the Northern
     * and Central lines ever produce a value — they are the only two that split,
     * rejoin, AND get labelled by TfL — so an explicit null would ride on every
     * departure of every other line, on every stream frame, to say nothing.
     *
     * Clients must treat absent exactly as they treat any unrecognised value:
     * FAIL OPEN, and show the train. Reading a missing branch as "not on my
     * branch" would hide services on the whole rest of the network.
     *
     * Stamped for every producer at `PredictionCache.set`, not in the sources.
     * There are two producers — our own TypeScript sources and the Java Syncer,
     * whose payloads are stored verbatim — and deriving it in a source covered
     * only the first, so the same station answered differently depending on who
     * wrote last.
     */
    viaKey?: string;
}

export interface DirectionPredictions {
    preds: PredictionItem[];
}

export interface LinePredictions {
    id: string;
    name: string;
    dirs: Record<string, DirectionPredictions>;
}

export interface StationPredictionResponse {
    id: string;
    name: string;
    lut: string; // Last Updated Time (ISO-8601)
    lines: Record<string, LinePredictions>;
}

export interface LineStatusResponse {
    id: string;
    name: string;
    statusSeverityDescription: string;
    reason?: string;
    mode: string;
    /** Epoch millis (integer) internally — the replication watermark. Formatted
     *  to an ISO-8601 string only at the API boundary (see `toIso`). */
    lastUpdatedTime: number;
}

export interface StationLineDetails {
    id: string;
    name: string;
    directions: string[];
}

export interface StationModeGroup {
    modeName: string;
    lines: Record<string, StationLineDetails>;
}

export interface Station {
    naptanId: string;
    commonName: string;
    lat: number;
    lon: number;
    geoHash?: string;
    stopType: string;
    indicator?: string;
    stopLetter?: string;
    /** Epoch millis (integer) — replication watermark. */
    lastUpdatedTime?: number;
    modes: Record<string, StationModeGroup>;
    searchKeys: string[];
    // Grouping keys (bus stops share icsCode / stationNaptan across directions)
    icsCode?: string;
    stationNaptan?: string;
    towards?: string;
    compassPoint?: string;
    // SDUI & Search Extras
    id?: string;
    label?: string;
    isMajor?: boolean;
    distance?: number;
    members?: string[]; // naptanIds of all grouped stops (set at query time, not stored)
}
