/**
 * Models mapping exactly to the responses generated by StationlyBE (Java)
 * This ensures strict contract adherence so UI integrations do not break.
 */

export interface TransportMode {
    modeName: string;
    displayName: string;
}

export interface LineInfo {
    id: string;
    name: string;
    modeName: string;
}

export interface Destination {
    id: string;
    name: string;
}

export interface DirectionInfo {
    direction: string; // e.g., inbound, outbound
    destinations: Destination[];
}

export interface LineRouteResponse {
    id: string;
    name: string;
    modeName: string;
    directions: DirectionInfo[];
}

export interface PredictionItem {
    destId: string;
    platform: string;
    eta: string; // ISO-8601
    displayName: string;
}

export interface DirectionPredictions {
    preds: PredictionItem[];
}

export interface LinePredictions {
    id: string;
    name: string;
    dirs: Record<string, DirectionPredictions>;
}

export interface StationPredictionResponse {
    id: string;
    name: string;
    lut: string; // Last Updated Time (ISO-8601)
    lines: Record<string, LinePredictions>;
}

export interface LineStatusResponse {
    id: string;
    name: string;
    statusSeverityDescription: string;
    reason?: string;
    mode: string;
    lastUpdatedTime: string;
}

export interface StationLineDetails {
    id: string;
    name: string;
    directions: string[];
}

export interface StationModeGroup {
    modeName: string;
    lines: Record<string, StationLineDetails>;
}

export interface Station {
    naptanId: string;
    commonName: string;
    lat: number;
    lon: number;
    geoHash?: string;
    stopType: string;
    indicator?: string;
    stopLetter?: string;
    lastUpdatedTime?: string;
    modes: Record<string, StationModeGroup>;
    searchKeys: string[];
}
